---
- name: Configure ansible
  hosts: localhost

  tasks:
    - name: Link .ansible.cfg
      ansible.builtin.file:
        src: '{{ ansible_env.PWD }}/../ansible.cfg'
        dest: '{{ ansible_env.HOME }}/.ansible.cfg'
        state: link

    - name: Install ansible-lint
      ansible.builtin.command: pipx install ansible-lint

