---
- name: Configure ansible
  hosts: localhost

  vars:
    asdf_home: '{{ ansible_env.HOME }}/.asdf'

  environment:
    PATH: "{{ asdf_home }}/bin:{{ asdf_home }}/shims:{{ ansible_env.PATH }}"

  tasks:
    - name: Link .ansible.cfg
      ansible.builtin.file:
        src: '{{ ansible_env.PWD }}/../ansible.cfg'
        dest: '{{ ansible_env.HOME }}/.ansible.cfg'
        state: link

    - name: Install ansible-lint
      ansible.builtin.command: pipx install ansible-lint

