---
- name: Configure GitHub CLI (gh)
  hosts: localhost

  vars:
    gh_home: '{{ ansible_env.HOME }}/.config/gh'

  tasks:
    ###########################
    # gh
    # GitHub’s official command line tool
    ###########################
    - name: MacOS => install gh
      when: ansible_distribution == 'MacOSX'
      community.general.homebrew:
        name: gh

    - name: Ubuntu => install gh
      when: ansible_distribution == 'Ubuntu'
      ansible.builtin.shell:
        (type -p wget >/dev/null || (sudo apt update && sudo apt install wget -y)) \
          && sudo mkdir -p -m 755 /etc/apt/keyrings \
          && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
          && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && sudo mkdir -p -m 755 /etc/apt/sources.list.d \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      become: true

    - name: Create gh config directory
      ansible.builtin.file:
        path: '{{ gh_home }}'
        state: directory
        mode: 0755

    - name: Link config.yml
      ansible.builtin.file:
        src: '{{ ansible_env.PWD }}/../../gh/config.yml'
        dest: '{{ gh_home }}/config.yml'
        state: link
        force: true
