---
- name: Configure git
  hosts: localhost

  tasks:
    ###########################
    # git
    # A free and open source distributed version control system designed
    # to handle everything from small to very large projects with speed
    # and efficiency
    ###########################
    - name: MacOS => install git
      when: ansible_distribution == 'MacOSX'
      community.general.homebrew:
        name: git

    - name: Ubuntu => install git
      when: ansible_distribution == 'Ubuntu'
      apt:
        name: git
        state: latest
      become: true

    ###########################
    # git-flow
    # An alternative Git branching model that involves the use of feature
    # branches and multiple primary branches
    ###########################
    - name: MacOS => install git-flow
      when: ansible_distribution == 'MacOSX'
      community.general.homebrew:
        name: git-flow

    - name: Ubuntu => install git-flow
      when: ansible_distribution == 'Ubuntu'
      apt:
        name: git-flow
        state: latest
      become: true

    - name: Link .gitconfig
      ansible.builtin.file:
        src: '{{ ansible_env.PWD }}/../../git/gitconfig'
        dest: '{{ ansible_env.HOME }}/.gitconfig'
        state: link
        force: true
