---
- name: Configure IDEA
  hosts: localhost

  tasks:
    - name: MacOS => install IDEA
      when: ansible_distribution == 'MacOSX'
      community.general.homebrew_cask:
        name: intellij-idea-ce

    - name: Link .ideavimrc
      ansible.builtin.file:
        src: '{{ ansible_env.PWD }}/../../idea/ideavimrc'
        dest: '{{ ansible_env.HOME }}/.ideavimrc'
        state: link
        force: true
