- name: Configure mycli
  hosts: localhost

  tasks:
    - name: Install mycli
      ansible.builtin.pip:
        name: mycli

    - name: Link .my.cnf
      ansible.builtin.file:
        src: '{{ ansible_env.PWD }}/../../mycli/my.cnf'
        dest: '{{ ansible_env.HOME }}/.my.cnf'
        state: link
        force: true

    - name: Link .myclirc
      ansible.builtin.file:
        src: '{{ ansible_env.PWD }}/../../mycli/myclirc'
        dest: '{{ ansible_env.HOME }}/.myclirc'
        state: link
        force: true
