- name: Configure mycli
  hosts: localhost

  vars:
    asdf_home: '{{ ansible_env.HOME }}/.asdf'

  environment:
    PATH: "{{ asdf_home }}/bin:{{ asdf_home }}/shims:{{ ansible_env.PATH }}"

  tasks:
    - name: Install mycli
      ansible.builtin.command: pipx install mycli

    - name: Link .my.cnf
      ansible.builtin.file:
        src: '{{ ansible_env.PWD }}/../../mycli/my.cnf'
        dest: '{{ ansible_env.HOME }}/.my.cnf'
        state: link
        force: true

    - name: Link .myclirc
      ansible.builtin.file:
        src: '{{ ansible_env.PWD }}/../../mycli/myclirc'
        dest: '{{ ansible_env.HOME }}/.myclirc'
        state: link
        force: true
