---
- name: Configure nerd fonts
  hosts: localhost

  tasks:
    ###########################
    # Nerd Fonts
    # Patches developer targeted fonts with a high number of glyphs (icons).
    ###########################
    - name: MacOS => install nerd fonts
      when: ansible_distribution == 'MacOSX'
      ansible.builtin.shell: |
        declare -a fonts=(
          font-fira-code-nerd-font
          font-hack-nerd-font
        )

        for font in "${fonts[@]}"; do
          brew install --cask "$font"
        done

    - name: Ubuntu => Install nerd fonts
      when: ansible_distribution == 'Ubuntu'
      ansible.builtin.shell: |
        declare -a fonts=(
            FiraCode
            Hack
        )

        version='2.1.0'
        fonts_dir="${HOME}/.local/share/fonts"

        if [[ ! -d "$fonts_dir" ]]; then
          mkdir -p "$fonts_dir"
        fi

        for font in "${fonts[@]}"; do
          zip_file="${font}.zip"
          download_url="https://github.com/ryanoasis/nerd-fonts/releases/download/v${version}/${zip_file}"
          echo "Downloading $download_url"
          wget "$download_url"
          unzip "$zip_file" -d "$fonts_dir"
          rm "$zip_file"
        done

        find "$fonts_dir" -name '*Windows Compatible*' -delete

        fc-cache -fv
      become: true
