---
- name: Configure nvim
  hosts: localhost

  vars:
    asdf_home: '{{ ansible_env.HOME }}/.asdf'

  environment:
    PATH: "{{ asdf_home }}/bin:{{ asdf_home }}/shims:{{ ansible_env.PATH }}"

  tasks:
    - name: MacOS => install neovim
      when: ansible_distribution == 'MacOSX'
      community.general.homebrew:
        name: neovim

    - name: Add neovim unstable repository from PPA
      when: ansible_distribution == 'Ubuntu'
      ansible.builtin.apt_repository:
        repo: ppa:neovim-ppa/unstable
        state: present
      become: true

    - name: Ubuntu => install neovim
      when: ansible_distribution == 'Ubuntu'
      apt:
        name: neovim
        state: latest
      become: true

    - name: Create nvim config directory
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/.config/nvim'
        state: directory
        mode: 0755

    - name: Link .vimrc
      ansible.builtin.file:
        src: '{{ ansible_env.PWD }}/../../nvim/vimrc'
        dest: '{{ ansible_env.HOME }}/.vimrc'
        state: link
        force: true

    - name: Create lua config directory
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/.config/nvim/lua'
        state: directory
        mode: 0755

    - name: Link init.vim
      ansible.builtin.file:
        src: '{{ ansible_env.PWD }}/../../nvim/init.vim'
        dest: '{{ ansible_env.HOME }}/.config/nvim/init.vim'
        state: link
        force: true

    - name: Link init.lua
      ansible.builtin.file:
        src: '{{ ansible_env.PWD }}/../../nvim/init.lua'
        dest: '{{ ansible_env.HOME }}/.config/nvim/lua/init.lua'
        state: link
        force: true

    - name: Link coc-settings.json
      ansible.builtin.file:
        src: '{{ ansible_env.PWD }}/../../nvim/coc-settings.json'
        dest: '{{ ansible_env.HOME }}/.config/nvim/coc-settings.json'
        state: link
        force: true

    - name: Install vim-plug
      ansible.builtin.shell: >
        curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
          https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    - name: Create a directory for lombok.jar
      when: not ansible_check_mode
      ansible.builtin.file:
        path: '/usr/local/share/lombok'
        state: directory
        mode: 0777
        recurse: true
      become: true

    - name: Download the latest lombok.jar (https://projectlombok.org/)
      when: not ansible_check_mode
      ansible.builtin.get_url:
        url: 'https://projectlombok.org/downloads/lombok-1.18.30.jar'
        dest: '/usr/local/share/lombok/lombok-1.18.30.jar'
        mode: 0775

    - name: Install neovim `python3` provider (Run :checkhealth provider)
      ansible.builtin.pip:
        name: neovim

    - name: Install pynvim (support `pyx` command)
      ansible.builtin.pip:
        name: pynvim

    - name: Install autopep8 (support `autopep8` command for python formatter)
      ansible.builtin.pip:
        name: autopep8
