---
- name: Preflight
  hosts: localhost

  tasks:
    - name: MacOS => homebrew upgrade all casks
      when: ansible_distribution == 'MacOSX'
      community.general.homebrew_cask:
        update_homebrew: true
        upgrade_all: true
        sudo_password: "{{ ansible_become_pass }}"

    - name: MacOS => homebrew upgrade all formulas
      when: ansible_distribution == 'MacOSX'
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true

    - name: Ubuntu => apt upgrade all
      when: ansible_distribution == 'Ubuntu'
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600   # Only One Hour
      become: true

