- name: Configure taskwarrior
  hosts: localhost

  tasks:
    - name: MacOS => install taskwarriror
      when: ansible_distribution == 'MacOSX'
      community.general.homebrew:
        name: task

    - name: Create task config directory
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/.config/task'
        state: directory
        mode: 0644

    - name: Link taskrc
      ansible.builtin.file:
        src: '{{ ansible_env.PWD }}/../../task/taskrc'
        dest: '{{ ansible_env.HOME }}/.config/task/taskrc'
        state: link
        force: true
