---
- name: Configure tmux
  hosts: localhost

  vars:
    tmux_home: '{{ ansible_env.HOME }}/.tmux'

  tasks:
    - name: MacOS => install tmux
      when: ansible_distribution == 'MacOSX'
      community.general.homebrew:
        name: tmux

    - name: Ubuntu => install tmux
      when: ansible_distribution == 'Ubuntu'
      apt:
        name: tmux
        state: latest
      become: true

    - name: Clone gpakosz/.tmux
      ansible.builtin.git:
        repo: https://github.com/gpakosz/.tmux.git
        dest: '{{ tmux_home }}'
        clone: true
        update: true
        force: true
        depth: 1

    - name: Clone tmux-plugins/tpm
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm.git
        dest: '{{ tmux_home }}/plugins/tpm'
        clone: true
        update: true
        force: true
        depth: 1

    - name: Link .tmux.conf
      ansible.builtin.file:
        src: '{{ tmux_home }}/.tmux.conf'
        dest: '{{ ansible_env.HOME }}/.tmux.conf'
        state: link
        force: true

    - name: Link .tmux.conf.local
      ansible.builtin.file:
        src: '{{ ansible_env.PWD }}/../../tmux/tmux.conf.local'
        dest: '{{ ansible_env.HOME }}/.tmux.conf.local'
        state: link
        force: true
