---
- name: Install virtualbox
  hosts: localhost

  tasks:
    - name: MacOS => install virtualbox
      when: ansible_distribution == 'MacOSX'
      community.general.homebrew_cask:
        name:
          - virtualbox
        sudo_password: "{{ ansible_become_pass }}"
